"""empty message

Revision ID: 091d25701a42
Revises: 1994447408d3
Create Date: 2023-03-09 13:19:27.501182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091d25701a42'
down_revision = '1994447408d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ontology_archive_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ontology_git_data', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ontology_archive_table', schema=None) as batch_op:
        batch_op.drop_column('ontology_git_data')

    # ### end Alembic commands ###
