"""empty message

Revision ID: 0cd9d6de5714
Revises: 095b4a157976
Create Date: 2022-07-08 15:09:19.373982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cd9d6de5714'
down_revision = '095b4a157976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sc3_user_model', schema=None) as batch_op:
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sc3_user_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
