"""empty message

Revision ID: 1994447408d3
Revises: a0c1e4743b8a
Create Date: 2022-08-08 17:47:09.819696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1994447408d3'
down_revision = 'a0c1e4743b8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_accesstype', sa.String(), nullable=True))
        batch_op.drop_column('project_accessType')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_accessType', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('project_accesstype')

    # ### end Alembic commands ###
