"""empty message

Revision ID: 4eb1067bbc1b
Revises: 05e91ee5fee6
Create Date: 2022-07-07 16:37:39.739577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eb1067bbc1b'
down_revision = '05e91ee5fee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sc3_user_model', schema=None) as batch_op:
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sc3_user_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
