"""empty message

Revision ID: 53de7cc845c3
Revises: 091d25701a42
Create Date: 2025-08-21 17:12:10.719424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '53de7cc845c3'
down_revision = '091d25701a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ontology_archive_table',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hash_id', sa.Integer(), nullable=False),
    sa.Column('uuid_entry', sa.String(), nullable=True),
    sa.Column('ontology_name', sa.String(), nullable=True),
    sa.Column('ontology_lookup_type', sa.String(), nullable=True),
    sa.Column('ontology_access_type', sa.String(), nullable=True),
    sa.Column('ontology_lookup_path', sa.String(), nullable=True),
    sa.Column('ontology_data', sa.String(), nullable=True),
    sa.Column('ontology_git_data', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('hash_id'),
    sa.UniqueConstraint('hash_id')
    )
    op.create_table('ontology_indexing_table',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hash_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('ontology_name', sa.String(), nullable=True),
    sa.Column('ontology_lookup_type', sa.String(), nullable=True),
    sa.Column('ontology_access_type', sa.String(), nullable=True),
    sa.Column('ontology_lookup_path', sa.String(), nullable=True),
    sa.Column('ontology_description', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('hash_id'),
    sa.UniqueConstraint('hash_id')
    )
    op.create_table('projects_table',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hash_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('project_description', sa.String(), nullable=True),
    sa.Column('project_accesstype', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('hash_id'),
    sa.UniqueConstraint('hash_id')
    )
    op.create_table('sc3_role_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sc3_user_model',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hash_id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('passwd_hash', sa.String(), nullable=True),
    sa.Column('auth_type', sa.String(), nullable=True),
    sa.Column('email_valid', sa.Boolean(), nullable=True),
    sa.Column('account_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('hash_id'),
    sa.UniqueConstraint('hash_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('sc3_project_ontologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('ontology_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontology_indexing_table.hash_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects_table.hash_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sc3_users_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects_table.hash_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sc3_user_model.hash_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sc3_users_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['sc3_role_model.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sc3_user_model.hash_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sc3_vote_model',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hash_id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('term_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UNDER_AGREEMENT', 'UNDER_REVISION', 'APPROVED', 'REJECTED', 'CLOSED', name='votestatus'), nullable=False),
    sa.Column('type', sa.Enum('ACCEPT', 'REJECT', name='votetype'), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['sc3_user_model.hash_id'], ),
    sa.PrimaryKeyConstraint('hash_id'),
    sa.UniqueConstraint('hash_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('sc3_decision_model',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('choice', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['sc3_user_model.hash_id'], ),
    sa.ForeignKeyConstraint(['vote_id'], ['sc3_vote_model.hash_id'], ),
    sa.PrimaryKeyConstraint('id', 'vote_id', 'user_id')
    )
    op.create_table('sc3_discussion_model',
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vote_id'], ['sc3_vote_model.hash_id'], ),
    sa.PrimaryKeyConstraint('vote_id')
    )
    op.create_table('sc3_comment_model',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hash_id', sa.Integer(), nullable=False),
    sa.Column('discussion_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['discussion_id'], ['sc3_discussion_model.vote_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sc3_user_model.hash_id'], ),
    sa.PrimaryKeyConstraint('hash_id'),
    sa.UniqueConstraint('hash_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sc3_comment_model')
    op.drop_table('sc3_discussion_model')
    op.drop_table('sc3_decision_model')
    op.drop_table('sc3_vote_model')
    op.drop_table('sc3_users_roles')
    op.drop_table('sc3_users_projects')
    op.drop_table('sc3_project_ontologies')
    op.drop_table('sc3_user_model')
    op.drop_table('sc3_role_model')
    op.drop_table('projects_table')
    op.drop_table('ontology_indexing_table')
    op.drop_table('ontology_archive_table')
    # ### end Alembic commands ###
