"""Update VoteStatus enum values

Revision ID: 6eb2a1b9155b
Revises: 53de7cc845c3
Create Date: 2025-11-21 11:25:31.294493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb2a1b9155b'
down_revision = '53de7cc845c3'
branch_labels = None
depends_on = None


def upgrade():

    op.execute("ALTER TYPE votestatus rename value 'APPROVED' to 'ACCEPT'")
    op.execute("ALTER TYPE votestatus rename value 'REJECTED' to 'NOT_ACCEPT'")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sc3_comment_model', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['hash_id'])

    with op.batch_alter_table('sc3_vote_model', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['hash_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sc3_vote_model', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('sc3_comment_model', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
