"""empty message

Revision ID: 7fc7022f9ba5
Revises: 917d13774849
Create Date: 2022-06-28 17:39:49.795170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc7022f9ba5'
down_revision = '917d13774849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sc3_users_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects_table.hash_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sc3_user_model.hash_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ontology_archive_table', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['hash_id'])

    with op.batch_alter_table('ontology_indexing_table', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['hash_id'])

    with op.batch_alter_table('projects_table', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['hash_id'])

    with op.batch_alter_table('sc3_user_model', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['hash_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sc3_user_model', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('projects_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('ontology_indexing_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('ontology_archive_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('sc3_users_projects')
    # ### end Alembic commands ###
