"""empty message

Revision ID: 917d13774849
Revises: 
Create Date: 2022-06-21 18:58:34.144277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '917d13774849'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ontology_archive_table',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hash_id', sa.Integer(), nullable=False),
    sa.Column('uuid_entry', sa.String(), nullable=True),
    sa.Column('ontology_name', sa.String(), nullable=True),
    sa.Column('ontology_lookup_type', sa.String(), nullable=True),
    sa.Column('ontology_access_type', sa.String(), nullable=True),
    sa.Column('ontology_lookup_path', sa.String(), nullable=True),
    sa.Column('ontology_data', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('hash_id'),
    sa.UniqueConstraint('hash_id')
    )
    op.create_table('ontology_indexing_table',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hash_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('ontology_name', sa.String(), nullable=True),
    sa.Column('ontology_lookup_type', sa.String(), nullable=True),
    sa.Column('ontology_access_type', sa.String(), nullable=True),
    sa.Column('ontology_lookup_path', sa.String(), nullable=True),
    sa.Column('ontology_description', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('hash_id'),
    sa.UniqueConstraint('hash_id')
    )
    op.create_table('projects_table',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hash_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('project_description', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('hash_id'),
    sa.UniqueConstraint('hash_id')
    )
    op.create_table('sc3_role_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sc3_user_model',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hash_id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('passwd_hash', sa.String(), nullable=True),
    sa.Column('auth_type', sa.String(), nullable=True),
    sa.Column('email_valid', sa.Boolean(), nullable=True),
    sa.Column('account_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('hash_id'),
    sa.UniqueConstraint('hash_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('sc3_project_ontologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('ontology_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontology_indexing_table.hash_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects_table.hash_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sc3_users_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['sc3_role_model.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sc3_user_model.hash_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sc3_users_roles')
    op.drop_table('sc3_project_ontologies')
    op.drop_table('sc3_user_model')
    op.drop_table('sc3_role_model')
    op.drop_table('projects_table')
    op.drop_table('ontology_indexing_table')
    op.drop_table('ontology_archive_table')
    # ### end Alembic commands ###
