"""(Decision model): Add Unique constraint on user_id + vote_id

Revision ID: 93802f7930cf
Revises: 6eb2a1b9155b
Create Date: 2026-01-28 13:00:34.107897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93802f7930cf'
down_revision = '6eb2a1b9155b'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("ALTER TYPE votestatus ADD VALUE 'DRAFT'")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sc3_decision_model', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_vote', ['user_id', 'vote_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sc3_decision_model', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_vote', type_='unique')

    # ### end Alembic commands ###
