"""empty message

Revision ID: 9f0cf1a13fc8
Revises: 7fc7022f9ba5
Create Date: 2022-07-07 12:19:02.177351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0cf1a13fc8'
down_revision = '7fc7022f9ba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sc3_user_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sc3_user_model', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
