"""empty message

Revision ID: a0c1e4743b8a
Revises: 0cd9d6de5714
Create Date: 2022-07-19 17:09:20.548143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0c1e4743b8a'
down_revision = '0cd9d6de5714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_accessType', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects_table', schema=None) as batch_op:
        batch_op.drop_column('project_accessType')

    # ### end Alembic commands ###
