"""New Subscription Model

Revision ID: d7ef128d53ec
Revises: 93802f7930cf
Create Date: 2026-03-04 16:13:46.735909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ef128d53ec'
down_revision = '93802f7930cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sc3_push_subscription_model',
    sa.Column('hash_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('p256dh', sa.String(), nullable=False),
    sa.Column('auth', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['sc3_user_model.hash_id'], ),
    sa.PrimaryKeyConstraint('hash_id'),
    sa.UniqueConstraint('hash_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sc3_push_subscription_model')
    # ### end Alembic commands ###
